### ISSUE TITLE
Caida de servicio API después de error de encabezados

### ISSUE THREAD

**Issue by danflop** [LBAB-Humboldt/biomodelos_db_api#8]
Se presenta una pérdida de conexión con la API de la base de datos de BioModelos después de presentarse el siguiente error en el servicio:

![error_api_biomodelos](https://cloud.githubusercontent.com/assets/5290060/23713577/64506190-03f4-11e7-8434-fcd276a75404.png)

`_http_outgoing.js:344
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.res.set.res.header (/home/gicbd/BioModelos/node_modules/ex                                                                                                                                                      press/lib/response.js:524:10)
    at ServerResponse.res.json (/home/gicbd/BioModelos/node_modules/express/lib/                                                                                                                                                      response.js:189:36)
    at /home/gicbd/BioModelos/server.js:669:21
    at /home/gicbd/BioModelos/node_modules/mongoose/node_modules/kareem/index.js                                                                                                                                                      :109:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

`

**Comment by valegrajales** [comment]
Criterio de aceptación: Prueba de carga usando JMeter para un estimado de 1000 usuarios concurrentes. La prueba debe pasar con esta carga persistente durante 3 minutos.

**Comment by rickreyjim1** [comment]
Prueben a comentar el campo res.json({message:"djfhufod"})
